### ISSUE TITLE
Unable to handle th[colspan=2] selector

### ISSUE THREAD

**Issue by Paradoxis** [facelessuser/soupsieve#144]
After upgrading BeautifulSoup from `4.6.3` to `4.7.x` my CI fails with the following stack trace:

```
Traceback (most recent call last):
  ...
  File "/builds/ci/project/parsers/parser.py", line 48, in test
   len(table.select("th[colspan=2]")) == 1 and
  File "/builds/ci/project/venv/lib/python3.7/site-packages/bs4/element.py", line 1376, in select
    return soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/builds/ci/project/venv/lib/python3.7/site-packages/soupsieve/__init__.py", line 114, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/builds/ci/project/venv/lib/python3.7/site-packages/soupsieve/__init__.py", line 63, in compile
    return cp._cached_css_compile(pattern, namespaces, custom, flags)
  File "/builds/ci/project/venv/lib/python3.7/site-packages/soupsieve/css_parser.py", line 214, in _cached_css_compile
    CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
  File "/builds/ci/project/venv/lib/python3.7/site-packages/soupsieve/css_parser.py", line 1113, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/builds/ci/project/venv/lib/python3.7/site-packages/soupsieve/css_parser.py", line 946, in parse_selectors
    key, m = next(iselector)
  File "/builds/ci/project/venv/lib/python3.7/site-packages/soupsieve/css_parser.py", line 1100, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
  File "<string>", line None
soupsieve.util.SelectorSyntaxError: Malformed attribute selector at position 2
  line 1:
th[colspan=2]
  ^
```

The issue is caused by running the following snippet of Python code:

```python
element.select("th[colspan=2]")
```

**Comment by facelessuser** [comment]
I believe later versions of soupsieve give a better error, but yup, that is according to the CSS spec. Checkout the differences between what soupsieve does, and the old select library: https://facelessuser.github.io/soupsieve/differences/.

In short, you'll have to either quote the `2`, or use a CSS escape.

**Comment by Paradoxis** [comment]
Confirmed: Changing it to `'th[colspan="2"]'` did the trick for me, thanks
