### ISSUE TITLE
missing dependency on `bs4`

### ISSUE THREAD

**Issue by asottile-sentry** [facelessuser/soupsieve#251]
```console
$ pip install soupsieve
Collecting soupsieve
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve
Successfully installed soupsieve-2.3.2.post1
$ python3 -c 'import soupsieve'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/y/venv/lib/python3.10/site-packages/soupsieve/__init__.py", line 29, in <module>
    from . import css_parser as cp
  File "/tmp/y/venv/lib/python3.10/site-packages/soupsieve/css_parser.py", line 5, in <module>
    from . import css_match as cm
  File "/tmp/y/venv/lib/python3.10/site-packages/soupsieve/css_match.py", line 7, in <module>
    import bs4  # type: ignore[import]
```

I understand `soupsieve` is intended to be used with beautifulsoup but it isn't even importable without it installed -- soupsieve should probably have an `install_requires` (or whatever the hatch-equivalent is) that include `beautifulsoup4`

**Comment by facelessuser** [comment]
Yep, nor will it be.  The reason is we didn't want to create a circular dependency. Originally, we weren't sure that it would be accepted as the official CSS selector library of BeautifulSoup. If it had not been accepted, we would have had to require `bs4` as a dependency.

Generally, it is expected that you will get the package by installing `bs4`, but if you don't, you will need to install `bs4`.

**Comment by asottile-sentry** [comment]
is there a problem with a cycle there?  it's already cyclical but the metadata doesn't match that

**Comment by facelessuser** [comment]
Most people aren't going to install soupsieve directly.

Now, this shouldn't be a surprise either as we do document this fact [here](https://github.com/facelessuser/soupsieve#installation) and [here](https://facelessuser.github.io/soupsieve/#installation).

I have had some projects that have created this circular dependency before, and this is especially problematic for people using tools to pin certain package versions, like when using [Poetry](https://python-poetry.org/) or other package management systems. In these cases, people will complain about the circular dependency.

So, this is a lose-lose situation for me. I'll have people complain if I don't create the circular link, and I'll have people that will complain if I do create the circular link. So, end the end, I chose the path that doesn't actually break anything. Yes, if you don't have `bs4`, `soupsieve` won't work, but if you install `bs4`, it will work fine. The alternative is I break things like Poetry with no resolution.

**Comment by asottile-sentry** [comment]
in my experience poetry handles cycles fine -- do you have a link to a failure there?
